@startuml
/' @author @akhilvuputuri @jarrod-bob'/

start

:Enter Diet Tracker;



if () then ([allMetricsEntered])

else ([else])
    if () then ([bothHeightWeightEntered])
        if () then ([modeEntered])

        else ([else])
            : Mode Command;
        endif
    else ([else])
        if () then ([onlyHeightOrWeightEntered])
            if () then ([onlyHeightEntered])
                : Weight Command;
            else ([else])
                : Height Command;
            endif
        else ([else])
            : Height Command;
            : Weight Command;
        endif
        if () then ([modeEntered])

                else ([else])
                    : Mode Command;
                endif
    endif

endif


: Add Command;

: List Command;

stop
@enduml
